lib-app/config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users, :libraries


  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  post '/sessions', to: 'sessions#create'

  get 'users/:user_id/libraries', to: 'library_users#index', as: 'user_libraries'
  post '/libraries/:library_id/users', to: 'library_users#create', as: 'library_users'

end

lib-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lib-app/app/models/library.rb
class Library < ApplicationRecord
  has_many :library_users, dependent: :destroy
  has_many :users, through: :library_users
end

lib-app/app/models/library_user.rb
class LibraryUser < ApplicationRecord
  belongs_to :user
  belongs_to :library
end

lib-app/app/models/user.rb
class User < ApplicationRecord

  has_many :library_users, dependent: :destroy
  has_many :libraries, through: :library_users

  has_secure_password

  def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user ? @user.authenticate(params[:password]) : false
  end

end

lib-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

lib-app/app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController

  def index
    @libraries = Library.all
  end

  def new
    @library = Library.new
  end

  def create
    @library = Library.create(library_params)
    redirect_to libraries_path
  end

  def show
    @library = Library.find_by_id(params[:id])
  end

  private

    def library_params
      params.require(:library).permit(:name, :floor_count, :floor_area)
    end

end

lib-app/app/controllers/library_users_controller.rb
class LibraryUsersController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @libraries = @user.libraries
  end

  def create
    @library = Library.find(params[:library_id])
    @library.users.push(current_user)

    redirect_to current_user
  end

end

lib-app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notice] = "Successfully logged in."
      redirect_to @user
    else
      redirect_to login_path
      flash[:notice] = 'your creds are weak'
    end
  end

  def destroy
    logout
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end

end

lib-app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in?, only: [:show]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    login(@user)
    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

end

lib-app/app/helpers/application_helper.rb
module ApplicationHelper
end

lib-app/app/helpers/libraries_helper.rb
module LibrariesHelper
end

lib-app/app/helpers/library_users_helper.rb
module LibraryUsersHelper
end

lib-app/app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def logged_in?
    if session[:user_id] == nil
      redirect_to root_path
    end
  end

end

lib-app/app/helpers/users_helper.rb
module UsersHelper
end

lib-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% flash.each do |name, msg| %>
        <p>
          <small> <%= name.capitalize %>: <%= msg %> </small>
        </p>
      <% end %>

      <ul>
        <% if current_user %>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Log Out", logout_path %></li>
        <% else %>
          <li><%= link_to "Create Account", new_user_path %></li>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    <%= yield %>
  </body>
</html>

lib-app/app/views/libraries/index.html.erb
<h2>dem libraries!</h2>

<% @libraries.each do |library| %>
  <div>
    <h3><%= library.name %></h3>
    <% if current_user %>
      <%= button_to "Join", library_users_path(library) %>
    <% end %>
  </div>
  <br>
<% end %>

lib-app/app/views/libraries/new.html.erb
<%= form_for @library do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= f.number_field :floor_count, placeholder: "Floor Count" %>
  </div>
  <div>
    <%= f.number_field :floor_area, placeholder: "Floor Area" %>
  </div>
  <%= f.submit %>
<% end %>

lib-app/app/views/libraries/show.html.erb
<div>
  Welcome, <%= @library.name %>!
</div>

<p>You have <%= @library.floor_count %> floors!</p>

lib-app/app/views/library_users/index.html.erb
<div><%= @user.first_name %> is a member of the following libraries</div>

<ul>
  <% @libraries.each do |lib| %>
    <li><%= lib.name %></li>
  <% end %>
</ul>

lib-app/app/views/users/index.html.erb
<h2>You're on the users index!</h2>

<div>
There are currently <%= @users.length %> user(s) signed up!
</div>

lib-app/app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.text_field :first_name, placeholder: "First Name" %>
  </div>
  <div>
    <%= f.text_field :last_name, placeholder: "Last Name" %>
  </div>
  <div>
    <%= f.text_field :email, placeholder: "Email" %>
  </div>
  <div>
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
    <%= f.submit "Sign Up" %>

<% end %>

lib-app/app/views/users/show.html.erb
<div>
  Welcome, <%= @user.first_name %>!
</div>